before:
  hooks:
    - go mod tidy
    - make ui/build
builds:
  - main: ./cmd/parca/
    id: "parca"
    binary: parca
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
      - -v
    ldflags:
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
archives:
    # e.g. parca_0.15.0_Darwin_arm64.tar.gz, parca_0.15.0_Darwin_x86_64.tar.gz, parca_0.15.0_Linux_arm64.tar.gz, parca_0.15.0_Linux_x86_64.tar.gz
  - name_template: >-
      {{ .ProjectName }}_
      {{- trimprefix .Version "v" }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
source:
  enabled: true
release:
  prerelease: auto
  # Defaults to empty.
  footer: |
    ## Docker images

    `docker pull docker.io/zmj64351508/parca:{{ .Tag }}`

    ## Thanks!

    Join our [Discord server](https://discord.com/invite/ZgUpYgpzXy);
    Follow us on [Twitter](https://twitter.com/ParcaDev);
    Read the [documentation](https://www.parca.dev/docs/overview).
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
